cmake -S ./glfw -B ./glfw/build \
-DBUILD_SHARED_LIBS=ON \
-DGLFW_BUILD_EXAMPLES=OFF \
-DGLFW_BUILD_TESTS=OFF \
-DGLFW_BUILD_DOCS=OFF \
-DGLFW_INSTALL=OFF \
-DGLFW_BUILD_WAYLAND=ON \
-DGLFW_BUILD_WIN32=OFF \
-DGLFW_BUILD_COCOA=OFF \
-DGLFW_BUILD_X11=OFF \
-DGLFW_BUILD_WAYLAND=ON \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=$PWD/glfw/build/lib \
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$PWD/glfw/build/lib \
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$PWD/glfw/build/bin
cmake --build glfw/build
